#ifndef MICROSLAM_LOGGING_H
#define MICROSLAM_LOGGING_H

#include "slam/logging.h"

// Set the log level for the ESP-IDF logging system
#if SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_TRACE
#define LOG_LOCAL_LEVEL ESP_LOG_VERBOSE
#elif SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_DEBUG
#define LOG_LOCAL_LEVEL ESP_LOG_DEBUG
#elif SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_INFO
#define LOG_LOCAL_LEVEL ESP_LOG_INFO
#elif SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_WARN
#define LOG_LOCAL_LEVEL ESP_LOG_WARN
#elif SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_ERROR
#define LOG_LOCAL_LEVEL ESP_LOG_ERROR
#elif SLAM_LOG_LEVEL == SLAM_LOG_LEVEL_NONE
#define LOG_LOCAL_LEVEL ESP_LOG_NONE
#else
#define LOG_LOCAL_LEVEL ESP_LOG_INFO
#endif

#endif
