[workspace]
authors = ["Harry Jacobs <harry.jacobs@vaarst.com>"]
channels = ["conda-forge"]
name = "libmicroslam"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build_debug = "cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug && cmake --build build"
build_release = "cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release && cmake --build build"
test = { cmd = "ctest --test-dir build --output-on-failure", depends-on = ["build_debug"] }
clean = "rm -rf build"
app = "build/slam_test_app"

[dependencies]
cmake = "*"
ninja = "*"
gcc = "*"
glfw = ">=3"
mesa-libgl-devel-cos7-x86_64 = "*"
